[package]
name = "hackerrank"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"

[features]
hw1-task-1 = []
hw1-task-2 = []
hw1-task-3 = []
hw1 = ["hw1-task-1", "hw1-task-2", "hw1-task-3"]
