name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --features hw1
      - name: hw1-test-1
        run: cargo test --verbose --features hw1-test-1
      - name: hw1-test-2
        run: RUSTFLAGS="-C overflow-checks=on" RUST_BACKTRACE=full cargo test --verbose --features hw1-test-2
      - name: hw1-test-3
        run: cargo test --verbose --features hw1-test-3
